format = "${custom.machine}${custom.ssh}$directory$git_branch$git_status$line_break$character"

[custom.machine]
when = '''[ -z "${SSH_CONNECTION:-}${SSH_CLIENT:-}${SSH_TTY:-}${PROMPT_PURE_SSH_CONNECTION:-}" ]'''
shell = ["sh"]
symbol = "💻"
format = "$symbol "

[custom.ssh]
when = '''[ -n "${SSH_CONNECTION:-}${SSH_CLIENT:-}${SSH_TTY:-}${PROMPT_PURE_SSH_CONNECTION:-}" ]'''
shell = ["sh"]
symbol = "☁️"
format = "$symbol "

[directory]
style = "purple"
truncate_to_repo = false
truncation_length = 0

[git_branch]
format = "[$branch]($style) "
style = "bright-black"

[git_status]
disabled = true

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
